version: '3.8'

services:
  express:
    build: .
    environment:
      SESSION_SECRET: ${SESSION_SECRET}
      BACK_END_URL: ${BACK_END_URL}
      FRONT_END_URL: ${FRONT_END_URL}
      DATABASE_URL: ${DATABASE_URL}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    links:
      - database

  database:
    image: mongo:latest
    ports:
      - '27017:27017'

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    links:
      - express
