version: '3.8'

services:
  api:
    image: jonathanleedev/split-api:latest
    ports:
      - '80:3000'
    environment:
      SESSION_SECRET: ${SESSION_SECRET}
      BACK_END_URL: ${BACK_END_URL}
      FRONT_END_URL: ${FRONT_END_URL}
      DATABASE_URL: ${DATABASE_URL}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    volumes:
      - /etc/letsencrypt/live/api.split.jonathanlee.io/privkey.pem:/etc/letsencrypt/live/api.split.jonathanlee.io/privkey.pem
      - /etc/letsencrypt/live/api.split.jonathanlee.io/fullchain.pem:/etc/letsencrypt/live/api.split.jonathanlee.io/fullchain.pem
  database:
    image: mongo:latest
    ports:
      - '27017:27017'
