name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jonathanleedev/split-api:latest
    - uses: actions/checkout@v3
    - name: Push the Docker image
      run: docker push jonathanleedev/split-api:latest
